Remove Actions and Last Transaction column from Organizations table
bcgov/tfrs pull request #2580
Opened 2023-09-01 03:43 UTC by jig-patel

2023-09-01 18:15 UTC, AlexZorkin commented
This ticket also requires the removal of the actions column from the organizations excel download. In the SpreadsheetBuilder.py you'll have to update the add_fuel_suppliers method to remove this column when called by the organization viewset. The CreditTrade download also uses this method and currently we still want to include the actions column in that download.

2023-09-01 18:15 UTC, AlexZorkin requested changes
This ticket also requires the removal of the actions column from the organizations excel download. In the SpreadsheetBuilder.py you'll have to update the add_fuel_suppliers method to remove this column when called by the organization viewset. The CreditTrade download also uses this method and currently we still want to include the actions column in that download.

2023-09-01 21:45 UTC, jig-patel commented
Thansk @AlexZorkin .made changes to exclude actions from organization but keep it when downloading from creditTrade

2023-09-05 20:27 UTC, AlexZorkin approved these changes

2023-09-05 20:30 UTC, merged